"""Crear tablas contables base

Revision ID: 0e5870ff00e5
Revises: 
Create Date: 2026-02-18 00:55:09.740592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5870ff00e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cuentas_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_contables_codigo'), 'cuentas_contables', ['codigo'], unique=True)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cif'), 'empresas', ['cif'], unique=True)
    op.create_table('ejercicios_fiscales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False, comment='True=Abierto, False=Cerrado'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejercicios_fiscales_empresa_id'), 'ejercicios_fiscales', ['empresa_id'], unique=False)
    op.create_table('asientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios_fiscales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asientos_ejercicio_id'), 'asientos', ['ejercicio_id'], unique=False)
    op.create_index(op.f('ix_asientos_fecha'), 'asientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_asientos_numero'), 'asientos', ['numero'], unique=False)
    op.create_table('apuntes_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('debe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('haber', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apuntes_contables_asiento_id'), 'apuntes_contables', ['asiento_id'], unique=False)
    op.create_index(op.f('ix_apuntes_contables_cuenta_id'), 'apuntes_contables', ['cuenta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apuntes_contables_cuenta_id'), table_name='apuntes_contables')
    op.drop_index(op.f('ix_apuntes_contables_asiento_id'), table_name='apuntes_contables')
    op.drop_table('apuntes_contables')
    op.drop_index(op.f('ix_asientos_numero'), table_name='asientos')
    op.drop_index(op.f('ix_asientos_fecha'), table_name='asientos')
    op.drop_index(op.f('ix_asientos_ejercicio_id'), table_name='asientos')
    op.drop_table('asientos')
    op.drop_index(op.f('ix_ejercicios_fiscales_empresa_id'), table_name='ejercicios_fiscales')
    op.drop_table('ejercicios_fiscales')
    op.drop_index(op.f('ix_empresas_cif'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_cuentas_contables_codigo'), table_name='cuentas_contables')
    op.drop_table('cuentas_contables')
    # ### end Alembic commands ###
