"""Add Terceros table and Asiento FK

Revision ID: cffb13f840c8
Revises: 0e5870ff00e5
Create Date: 2026-02-18 06:38:53.147614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffb13f840c8'
down_revision: Union[str, Sequence[str], None] = '0e5870ff00e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cuentas_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terceros_nif'), ['nif'], unique=True)

    with op.batch_alter_table('asientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tercero_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_asientos_tercero_id'), ['tercero_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_asientos_tercero_id_terceros'), 'terceros', ['tercero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asientos', type_='foreignkey')
    op.drop_index(op.f('ix_asientos_tercero_id'), table_name='asientos')
    op.drop_column('asientos', 'tercero_id')
    op.drop_index(op.f('ix_terceros_nif'), table_name='terceros')
    op.drop_table('terceros')
    # ### end Alembic commands ###
